config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :answers
  resources :questions
  # resources :flags
  get 'welcome/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "/flag/:question_id/:user_id", to: "flags#create"
  post "/unflag/:question_id/:user_id", to: "flags#destroy"
  root to: "welcome#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  def compatibility(other)
    self_answers = Answer.where(profile_id: id).to_a
    other_answers = Answer.where(profile_id: other.id).to_a
    self_answers.product(other_answers).map do |x, y|
      x.score*y.score
    end.sum
  end

  def compatibilities
    Profile.all.map do |p|
      {
        id: p.id,
        ideology: p.ideology,
        compatibility: self.compatibility(p)
      }
    end.sort_by {|p| p[:compatibility]}
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    redirect_to new_user_session_path unless user_signed_in?
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    redirect_to new_user_session_path unless user_signed_in?
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    # puts "profile_params: #{profile_params}"
    # puts "params: #{params}"


    respond_to do |format|
      if @profile.save
        params["question"].each do |q, s|
          Answer.new(profile_id: @profile.id, question_id: q, score: s).save
        end
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :handle, :ideology)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  # Generate a cell of the compatibility table in views/profiles/show
  def compatibility_ranking_cell p
    content_tag(:td, link_to(p[:ideology], profile_path(p[:id])))
  end

  # Generate a row of the compatibility table in views/profiles/show
  def compatibility_ranking_row allies, rivals, i
    cells = compatibility_ranking_cell(allies[i])
    cells << compatibility_ranking_cell(rivals[i])
    content_tag :tr, cells
  end

  # Generate highest-variance 2D visualization of profiles
  # using PCA
  def profiles_map
    labels = Profile.all.map(&:ideology)
    data = pivot_table Profile, Question, Answer, :score
    visualize labels, data
  end

  # agglomerative clustering of profiles, by compatibility
  def profile_clusters
    profile_ids = Profile.all.map(&:id)
    compatibility_table = Profile.all.to_a.combination(2).map do |p1, p2|
      [[p1.id, p2.id], p1.compatibility(p2)]
    end.to_h
    points = pivot_table Profile, Question, Answer, "score"
    points_table = profile_ids.zip(points).to_h
    clusters = profile_ids.map {|x| [x]}
    # clusters = [[10, 12, 14, 17, 20, 22, 24], [13, 15, 16, 23], [18, 21], [19]]
    (2...clusters.count).map do
      centroids_table = clusters.map do |cluster|
        [cluster, centroid(cluster.map {|p| points_table[p]})]
      end.to_h
      # currently returns hash mapping clusters to their centroids
      clusters_to_merge = clusters.combination(2).min_by do |c1, c2|
        centroids_table[c1].zip(centroids_table[c2]).map do |s1, s2|
          (s1-s2)**2
        end.sum
      end
      new_cluster = clusters_to_merge.flatten
      clusters = clusters-clusters_to_merge+[clusters_to_merge.flatten]
      # recalculate centroids_table
      clusters_to_merge.each {|c| centroids_table.delete c}
      centroids_table[new_cluster] = centroid(new_cluster.map {|p| points_table[p]})
      data = compatibility_table.map do |profile_pair, compatibility|
        comrades = profile_pair.map do |p|
          clusters.find_index{|c| c.include? p}
        end.reduce(:==) ? 1 : 0
        [compatibility, comrades]
      end
      n, sx, sy, sxy, sx2, sy2 = [0, 0, 0, 0, 0, 0]
      data.each do |x, y|
        n += 1
        sx += x
        sy += y
        sxy += x*y
        sx2 += x*x
        sy2 += y*y
      end
      corr = (n*sxy-sx*sy)/Math.sqrt((n*sx2-sx*sx)*(n*sy2-sy*sy))
      [clusters, corr]
    end.max_by {|_, corr| corr}.first
  end

  private
  def centroid(cluster_points)
    cluster_points.transpose.map do |q|
      q.sum.to_f/q.count
    end
  end
end

app/views/profiles/_form.html.slim
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      h2 = "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      ul
        - @profile.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :handle
    = f.text_field :handle
  .field
    = f.label :ideology
    = f.text_field :ideology
  .actions = f.submit

app/views/profiles/edit.html.slim
h1 Editing profile

== render 'form'

=> link_to 'Show', @profile
'|
=< link_to 'Back', profiles_path

app/views/profiles/index.html.slim
h2 Proximity map of ideologies
h3
  ' Based on reduction to two dimensions using
  abbr title="principal component analysis" PCA
= profiles_map
h2 Recently added ideologies
ul
- Profile.last(30).reverse.each do |p|
  li
    => link_to profile_path(p)
      strong
        = p.ideology
    ' added by
    => p.handle
    ' on
    => p.updated_at.to_date.strftime

app/views/profiles/new.html.slim
= form_with url: profiles_path, class: "main-form" do |f|
  fieldset.profile
    legend.bold Please describe yourself to our community.
    = text_field :profile, :user_id, type: "hidden", value: current_user.id
    = label :profile, :handle, "display name"
    = text_field :profile, :handle, :required => true, :autofocus => true
    = label :profile, :ideology, "Please provide a short noun phrase which describes your personal worldview or ideology."
    = text_field :profile, :ideology, :required => true, :class => "wide"
  fieldset.questions
    legend.bold Please indicate your level of agreement with the following statements.
    - Question.all.sample(30).each do |q| # TODO: replace 30 w. some kind of settings thing
      fieldset.question 
        = label :answer, :question, q.question, class: "bold"
        - ["strongly disagree", "disagree", "neutral or no opinion", "agree", "strongly agree"].zip(-2..2).each do |desc, number|
          = label "question[#{number}]", :value, desc, class: "radio-label"
          = radio_button :question, q.id, number, class: "radio-button"
  =submit_tag "Enter your responses."

app/views/profiles/show.html.slim
h1
  = @profile.ideology
h2
  ' the stated ideology of
  span.red
    = @profile.handle
table
  caption likely allies and rivals
  thead
    tr
      th allies
      th rivals
  tbody
    - comps = @profile.compatibilities
    - n = [comps.count/2, 30].min
    - allies = comps.take n
    - rivals = comps.last(n).reverse
    - (0...n).each do |i|
      = compatibility_ranking_row allies, rivals, i
    