config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :answers
  resources :questions
  # resources :flags
  get 'welcome/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "/flag/:question_id/:user_id", to: "flags#create"
  post "/unflag/:question_id/:user_id", to: "flags#destroy"
  root to: "welcome#index"
end

app/views/layouts/application.html.slim
doctype html
html lang="en-us"
  head
    title
      = request.fullpath.split("/").reverse.join " "
    / = favicon_link_tag "favicon.ico"
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all", "data-turnbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
  body
    nav
      => link_to "\u{1f3e0}", welcome_index_path, :method => :get
      - if user_signed_in?
        => current_user.email
        ' &#9679;
        / h/t Jessie Dedecker http://stackoverflow.com/a/6557627/948073
        => link_to "sign out", destroy_user_session_path, :method => :delete
        - profile = Profile.find_by(user_id: current_user.id)
        - if profile.nil?
          ' Please fill out a profile
          => link_to "here", new_profile_path
          | so your potential allies can better find you.
        - else
          ' &#9679; Your ideology:
          => link_to profile.ideology, profile_path(profile)
          ' &#9679;
          => link_to "contribute a survey response item", new_question_path
      - else
        => link_to "sign up", new_user_registration_path, :method => :get
        => link_to "sign in", new_user_session_path, :method => :get
    div#undernav
      p class="notice"
        = notice
      p class="alert"
        = alert
      = yield